name: zzsn-nyse
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - pytorch=1.10.2
  - torchvision=0.2.2
  - pandas=1.4.2
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - unidecode=1.3.4
  - statsmodels=0.13.2
  - wandb=0.12.17
